import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Providers } from '@/redux/provider'
import SessionProviders from './SessionProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }): React.ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>
          <Providers>{children}</Providers>
        </SessionProviders>
      </body>
    </html>
  )
}
